spring:
    application:
      name: PLANS-API 
    boot:
      admin: 
        client:
          url: http://localhost:1002
    datasource:
     driver-class-name: com.mysql.jdbc.Driver
     password: abcd
     url: jdbc:mysql://localhost:3306/harish
     username: root
    jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761
management:
  endpoints:
    web:
      exposure:
        include: '*'
      
app:
  messages:
      PlanSavedSuccessfully : Plan Saved Successfully
      PlanNotSaved : Plan not Saved
      PlanDelted : Plan Deleted Succesfully
      planNotDeleted : Plan not Deleted
